# Data
SOURCE_DIR: 'C:\\TempDataForSpeed\\SINClassifierV2_20240812\\testset'
TARGET_DIR: 'D:\\CNN_Animal_ID\\SIN-classifier\\results\\SINClassifierV2\\testset'
CODEC: "mp4v"
VIS_MEDIA: False

# Model weights
DET_WEIGHTS_PATH: NULL
DET_VERSION: 'yolov9e' #yolov9c, yolov9e, yolov10n, or yolov10x
CLS_WEIGHTS_PATH: NULL
