## Arguments for video_to_crops.py
SOURCE_DIR: 'C:/TempDataForSpeed/SINClassifierV2_20240812/videos'
TARGET_DIR: 'C:/TempDataForSpeed/SINClassifierV2_20240812/cropped_resized'

## Arguments for train_model.py
dataset_root: 'C:\\TempDataForSpeed\\SINClassifierV2_20240812'
# training
conf_id: SINClassifierV2_20240812
algorithm: RSG
num_epochs: 200
log_interval: 10
parallel: 0
# data loading
dataset_name: Custom_Crop
batch_size: 128
num_workers: 20
# model
model_name: RSGResNet
num_layers: 50
num_classes: 35
loss_type: LDAM #CE, LDAM, or Focal
# RSG
head_lists: [1,2,3,4,7,14,15,16,17,19,22,23,25]
epoch_thresh: 90
# optimisation
train_rule: DRW #None, Reweight, or DRW
lr_feature: 0.1
momentum_feature: 0.9
weight_decay_feature: 0.0005
lr_classifier: 0.1
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
step_size: 30
gamma: 0.1